# frozen_string_literal: true

require "suma/commerce"
require "suma/postgres/model"
require "suma/image"
require "suma/translated_text"
require "suma/admin_linked"

class Suma::Commerce::Offering < Suma::Postgres::Model(:commerce_offerings)
  include Suma::Image::AssociatedMixin
  include Suma::AdminLinked

  plugin :timestamps
  plugin :tstzrange_fields, :period
  plugin :translated_text, :description, Suma::TranslatedText

  one_to_many :fulfillment_options, class: "Suma::Commerce::OfferingFulfillmentOption"
  one_to_many :offering_products, class: "Suma::Commerce::OfferingProduct"
  one_to_many :carts, class: "Suma::Commerce::Cart"

  many_through_many :products,
                    [
                      [:commerce_offering_products, :offering_id, :id],
                    ],
                    class: "Suma::Commerce::Product",
                    left_primary_key: :id,
                    right_primary_key: :id,
                    read_only: true,
                    order: [:created_at, :id]

  many_through_many :orders,
                    [
                      [:commerce_carts, :offering_id, :id],
                      [:commerce_checkouts, :cart_id, :id],
                      # [:commerce_orders, :offering_id, :id],
                    ],
                    class: "Suma::Commerce::Order",
                    left_primary_key: :id,
                    right_primary_key: :checkout_id,
                    read_only: true,
                    order: [:created_at, :id]

  dataset_module do
    def available_at(t)
      return self.where(Sequel.pg_range(:period).contains(Sequel.cast(t, :timestamptz)))
    end
  end

  def rel_admin_link = "/commerce-offering/#{self.id}"
end

# Table: commerce_offerings
# ----------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                    | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at            | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at            | timestamp with time zone |
#  period                | tstzrange                | NOT NULL
#  description_id        | integer                  | NOT NULL
#  confirmation_template | text                     | NOT NULL DEFAULT ''::text
# Indexes:
#  commerce_offerings_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  commerce_offerings_description_id_fkey | (description_id) REFERENCES translated_texts(id)
# Referenced By:
#  commerce_carts                        | commerce_carts_offering_id_fkey                        | (offering_id) REFERENCES commerce_offerings(id)
#  commerce_offering_fulfillment_options | commerce_offering_fulfillment_options_offering_id_fkey | (offering_id) REFERENCES commerce_offerings(id)
#  commerce_offering_products            | commerce_offering_products_offering_id_fkey            | (offering_id) REFERENCES commerce_offerings(id)
#  images                                | images_commerce_offering_id_fkey                       | (commerce_offering_id) REFERENCES commerce_offerings(id)
# ----------------------------------------------------------------------------------------------------------------------------------------------------------
