# frozen_string_literal: true

require "suma/commerce"
require "suma/postgres/model"
require "suma/admin_linked"
class Suma::Commerce::OfferingProduct < Suma::Postgres::Model(:commerce_offering_products)
  include Suma::AdminLinked
  plugin :timestamps
  plugin :money_fields, :customer_price
  plugin :money_fields, :undiscounted_price

  many_to_one :product, class: "Suma::Commerce::Product"
  many_to_one :offering, class: "Suma::Commerce::Offering"

  dataset_module do
    def available
      return self.where(closed_at: nil)
    end
  end

  def available?
    return self.closed_at.nil?
  end

  def closed?
    return false if self.closed_at.nil?
    return true
  end

  def discounted?
    return false if self.undiscounted_price.nil?
    return false if self.customer_price == self.undiscounted_price
    return true
  end

  def discount_amount
    return self.undiscounted_price - self.customer_price
  end

  def rel_admin_link = "/product/#{self.id}"
end

# Table: commerce_offering_products
# ---------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                          | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at                  | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at                  | timestamp with time zone |
#  closed_at                   | timestamp with time zone |
#  product_id                  | integer                  | NOT NULL
#  offering_id                 | integer                  | NOT NULL
#  customer_price_cents        | integer                  | NOT NULL
#  customer_price_currency     | text                     | NOT NULL
#  undiscounted_price_cents    | integer                  | NOT NULL
#  undiscounted_price_currency | text                     | NOT NULL
# Indexes:
#  commerce_offering_products_pkey                         | PRIMARY KEY btree (id)
#  commerce_offering_products_product_id_offering_id_index | UNIQUE btree (product_id, offering_id) WHERE closed_at IS NULL
#  commerce_offering_products_offering_id_index            | btree (offering_id)
#  commerce_offering_products_product_id_index             | btree (product_id)
# Foreign key constraints:
#  commerce_offering_products_offering_id_fkey | (offering_id) REFERENCES commerce_offerings(id)
#  commerce_offering_products_product_id_fkey  | (product_id) REFERENCES commerce_products(id)
# Referenced By:
#  commerce_checkout_items | commerce_checkout_items_offering_product_id_fkey | (offering_product_id) REFERENCES commerce_offering_products(id)
# ---------------------------------------------------------------------------------------------------------------------------------------------
