# frozen_string_literal: true

require "suma/commerce"
require "suma/postgres/model"

class Suma::Commerce::OrderAuditLog < Suma::Postgres::Model(:commerce_order_audit_logs)
  plugin :state_machine_audit_log

  many_to_one :order, class: "Suma::Commerce::Order"
  many_to_one :actor, class: "Suma::Member"
end

# Table: commerce_order_audit_logs
# -----------------------------------------------------------------------------------------------
# Columns:
#  id           | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  at           | timestamp with time zone | NOT NULL
#  event        | text                     | NOT NULL
#  to_state     | text                     | NOT NULL
#  from_state   | text                     | NOT NULL
#  reason       | text                     | NOT NULL DEFAULT ''::text
#  messages     | jsonb                    | NOT NULL DEFAULT '[]'::jsonb
#  order_id     | integer                  | NOT NULL
#  actor_id     | integer                  |
#  machine_name | text                     | NOT NULL
# Indexes:
#  commerce_order_audit_logs_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  commerce_order_audit_logs_actor_id_fkey | (actor_id) REFERENCES members(id) ON DELETE SET NULL
#  commerce_order_audit_logs_order_id_fkey | (order_id) REFERENCES commerce_orders(id)
# -----------------------------------------------------------------------------------------------
