# frozen_string_literal: true

require "suma/i18n"
require "suma/postgres"
require "suma/message"

# TODO: We have some assumptions about SMS right now; when we add in email support into the UI,
# stuff like subscription groups will need per-channel optin/out behavior.
class Suma::Message::Preferences < Suma::Postgres::Model(:message_preferences)
  plugin :timestamps

  many_to_one :member, class: Suma::Member

  class SubscriptionGroup < Suma::TypedStruct
    attr_accessor :model, :optout_field, :key, :opted_in, :editable_state

    def editable? = self.editable_state == "on"

    def set_from_opted_in(optin)
      self.model.set(self.optout_field => !optin)
    end
  end

  def initialize(*)
    super
    self[:sms_enabled] = true if self[:sms_enabled].nil?
    self[:email_enabled] = false if self[:email_enabled].nil?
    self[:preferred_language] = "en" if self[:preferred_language].nil?
    self[:access_token] ||= SecureRandom.uuid
  end

  def sms_enabled? = self.sms_enabled
  def email_enabled? = self.email_enabled

  # @param [Suma::Message::Template] message
  def dispatch(message)
    message.language = self.preferred_language
    to = self.member
    sent = []
    sent << Suma::Message.dispatch(message, to, :sms) if self.sms_enabled?
    sent << Suma::Message.dispatch(message, to, :email) if self.email_enabled?
    return sent
  end

  # @return [Array<SubscriptionGroup>]
  def subscriptions
    groups = []
    groups << SubscriptionGroup.new(
      model: self,
      optout_field: :account_updates_sms_optout,
      key: :account_updates,
      opted_in: !self.account_updates_sms_optout,
      editable_state: "on",
    )
    groups << SubscriptionGroup.new(
      model: self,
      optout_field: :marketing_sms_optout,
      key: :marketing,
      opted_in: !self.marketing_sms_optout,
      editable_state: "on",
    )
    groups << SubscriptionGroup.new(key: :security, opted_in: true, editable_state: "off")
    return groups
  end

  def public_url = "#{Suma.app_url}/preferences-public?token=#{self.access_token}"

  def preferred_language_name
    return Suma::I18n::SUPPORTED_LOCALES.fetch(self.preferred_language).language
  rescue KeyError
    return "Invalid (#{self.preferred_language})"
  end

  def validate
    super
    self.validates_includes Suma::I18n.enabled_locale_codes, :preferred_language
  end

  # @!attribute sms_enabled
  # True if the member has a phone number and is okay receiving SMS.
  # Note that if sms_enabled is false, it will override any 'true' settings on individual subscription groups.
  # @return [TrueClass,FalseClass]

  # @!attribute email_enabled
  # True if the member has an email and can receive emails.
  # Note that if email_enabled is false, it will override any 'true' settings on individual subscription groups.
  # @return [TrueClass,FalseClass]

  # @!attribute account_updates_sms_optout
  # True if the user has opted out of receiving account update messages via SMS.
  # @return [TrueClass,FalseClass]

  # @!attribute account_updates_email_optout
  # @return [TrueClass,FalseClass]

  # @!attribute marketing_sms_optout
  # @return [TrueClass,FalseClass]

  # @!attribute marketing_email_optout
  # @return [TrueClass,FalseClass]
end

# Table: message_preferences
# -------------------------------------------------------------------------------------------------------
# Columns:
#  id                           | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at                   | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at                   | timestamp with time zone |
#  member_id                    | integer                  | NOT NULL
#  preferred_language           | text                     | NOT NULL
#  sms_enabled                  | boolean                  | NOT NULL
#  email_enabled                | boolean                  | NOT NULL
#  access_token                 | text                     | NOT NULL
#  account_updates_sms_optout   | boolean                  | NOT NULL DEFAULT false
#  account_updates_email_optout | boolean                  | NOT NULL DEFAULT false
#  marketing_sms_optout         | boolean                  | NOT NULL DEFAULT false
#  marketing_email_optout       | boolean                  | NOT NULL DEFAULT false
# Indexes:
#  message_preferences_pkey             | PRIMARY KEY btree (id)
#  message_preferences_access_token_key | UNIQUE btree (access_token)
#  message_preferences_member_id_key    | UNIQUE btree (member_id)
# Foreign key constraints:
#  message_preferences_member_id_fkey | (member_id) REFERENCES members(id)
# -------------------------------------------------------------------------------------------------------
