# frozen_string_literal: true

require "suma/postgres/model"
require "suma/admin_linked"

class Suma::Program::EnrollmentExclusion < Suma::Postgres::Model(:program_enrollment_exclusions)
  include Suma::AdminLinked

  plugin :timestamps

  many_to_one :program, class: "Suma::Program"
  many_to_one :member, class: "Suma::Member"
  many_to_one :role, class: "Suma::Role"
  many_to_one :created_by, class: "Suma::Member"

  # @return [Suma::Member,Suma::Role]
  def enrollee = self.member || self.role

  # @return ["Member","Role","NilClass"]
  def enrollee_type = self.enrollee.class.name.demodulize

  def rel_admin_link = "/program-enrollment-exclusion/#{self.id}"
end

# Table: program_enrollment_exclusions
# -------------------------------------------------------------------------------------------------------------
# Columns:
#  id            | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at    | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at    | timestamp with time zone |
#  created_by_id | integer                  |
#  program_id    | integer                  | NOT NULL
#  member_id     | integer                  |
#  role_id       | integer                  |
# Indexes:
#  program_enrollment_exclusions_pkey                     | PRIMARY KEY btree (id)
#  program_enrollment_exclusions_program_id_member_id_key | UNIQUE btree (program_id, member_id)
#  program_enrollment_exclusions_program_id_role_id_key   | UNIQUE btree (program_id, role_id)
#  program_enrollment_exclusions_member_id_index          | btree (member_id)
#  program_enrollment_exclusions_program_id_index         | btree (program_id)
#  program_enrollment_exclusions_role_id_index            | btree (role_id)
# Check constraints:
#  one_enrollee_set | (member_id IS NOT NULL AND role_id IS NULL OR member_id IS NULL AND role_id IS NOT NULL)
# Foreign key constraints:
#  program_enrollment_exclusions_created_by_id_fkey | (created_by_id) REFERENCES members(id) ON DELETE SET NULL
#  program_enrollment_exclusions_member_id_fkey     | (member_id) REFERENCES members(id) ON DELETE CASCADE
#  program_enrollment_exclusions_program_id_fkey    | (program_id) REFERENCES programs(id) ON DELETE CASCADE
#  program_enrollment_exclusions_role_id_fkey       | (role_id) REFERENCES roles(id) ON DELETE CASCADE
# -------------------------------------------------------------------------------------------------------------
