# frozen_string_literal: true

require "suma/postgres/model"

class Suma::Program::Pricing < Suma::Postgres::Model(:program_pricings)
  include Suma::AdminLinked

  plugin :timestamps
  plugin(Suma::Program::Has, nil, nil) { [self.program] }

  many_to_one :program, class: "Suma::Program"
  many_to_one :vendor_service, class: "Suma::Vendor::Service"
  many_to_one :vendor_service_rate, class: "Suma::Vendor::ServiceRate"

  class << self
    # Fetch the program pricings available to the member.
    # The result is sorted by vendor service rate ordinal, higher-first.
    # This means that if there are multiple rates for the same service,
    # the first one that appears should take precedence.
    def fetch_eligible_to(member, as_of:, dataset: nil)
      ds = dataset || self.dataset
      ds = ds.where(vendor_service: Suma::Vendor::Service.dataset.available_at(as_of))
      rows = ds.fetch_eligible_to(member, as_of:)
      rows.sort_by! { |pri| pri.vendor_service_rate.ordinal }
      return rows
    end
  end

  def rel_admin_link = "/program-pricing/#{self.id}"
end

# Table: program_pricings
# ------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                     | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at             | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at             | timestamp with time zone |
#  program_id             | integer                  | NOT NULL
#  vendor_service_id      | integer                  | NOT NULL
#  vendor_service_rate_id | integer                  | NOT NULL
# Indexes:
#  program_pricings_pkey                               | PRIMARY KEY btree (id)
#  program_pricings_program_id_vendor_service_id_index | UNIQUE btree (program_id, vendor_service_id)
#  program_pricings_vendor_service_rate_id_index       | btree (vendor_service_rate_id)
# Foreign key constraints:
#  program_pricings_program_id_fkey             | (program_id) REFERENCES programs(id) ON DELETE CASCADE
#  program_pricings_vendor_service_id_fkey      | (vendor_service_id) REFERENCES vendor_services(id) ON DELETE CASCADE
#  program_pricings_vendor_service_rate_id_fkey | (vendor_service_rate_id) REFERENCES vendor_service_rates(id) ON DELETE CASCADE
# ------------------------------------------------------------------------------------------------------------------------------
