# frozen_string_literal: true

require "suma/external_links"
require "suma/payment/instrument"
require "suma/postgres/model"

class Suma::Payment::Card < Suma::Postgres::Model(:payment_cards)
  include Suma::Payment::Instrument::Interface
  include Suma::Postgres::HybridSearch
  include Suma::ExternalLinks

  plugin :generated_columns
  plugin :hybrid_search
  plugin :timestamps
  plugin :soft_deletes

  dataset_module do
    def usable_for_funding = self.unexpired_as_of(Time.now)
    def usable_for_payout = self.where(1 => 0)
    def unexpired_as_of(t) = self.where { expires_at > Sequel[t] }
    def expired_as_of(t) = self.where { expires_at <= Sequel[t] }
  end

  def payment_method_type = "card"
  def usable_for_funding? = !self.expired?
  def usable_for_payout? = false
  def verified? = true

  def rel_admin_link = "/member/#{self.member&.id}"

  def institution
    inst = INSTITUTIONS[self.brand]
    inst ||= Suma::Payment::Institution.new(
      name: self.brand,
      logo: DEFAULT_INSTITUTION.logo_src,
      color: DEFAULT_INSTITUTION.color,
    )
    return inst
  end

  def stripe_id = self.stripe_json.fetch("id")
  def fingerprint = self.stripe_json.fetch("fingerprint")
  def last4  = self.stripe_json.fetch("last4")
  def brand  = self.stripe_json.fetch("brand")
  def name = "#{self.brand} x-#{self.last4}"
  def exp_month = self.stripe_json.fetch("exp_month")
  def exp_year = self.stripe_json.fetch("exp_year")
  def expires_at = Time.utc(self.exp_year, self.exp_month, 1).next_month
  def institution_name = self.institution.name

  def simple_label = self.name

  def stripe_card
    return @stripe_card ||= Stripe::Card.construct_from(stripe_json.deep_symbolize_keys)
  end

  def refetch_remote_data
    customer = self.stripe_json.fetch("customer")
    existing = Stripe::Customer.retrieve(customer).
      sources.
      find { |src| src.id == self.stripe_id }
    if existing.nil?
      msg = "Card[#{self.id}] with Stripe Customer #{customer} has no source with id #{self.stripe_id}"
      raise Suma::InvariantViolation, msg
    end
    self.stripe_json = existing.as_json
    @stripe_data = nil
  end

  def _external_links_self
    return [
      self._external_link(
        "Stripe Customer",
        "#{Suma::Stripe.app_url}/customers/#{self.stripe_json.fetch('customer')}",
      ),
    ]
  end

  def hybrid_search_fields
    return [
      :payment_method_type,
      :stripe_id,
      :last4,
      :brand,
      [:institution_name, self.institution.name],
      ["Owner", self.legal_entity.name],
    ]
  end

  def self.load_payment_icon_base64(name)
    b = Base64.strict_encode64(File.binread(Suma::DATA_DIR + "payment-icons/#{name}"))
    return "data:image/png;base64,#{b}"
  end

  INSTITUTIONS = {
    "Visa" => Suma::Payment::Institution.new(
      name: "Visa",
      logo: self.load_payment_icon_base64("visa.png"),
      color: "#1A1F71",
    ),
    "MasterCard" => Suma::Payment::Institution.new(
      name: "MasterCard",
      logo: self.load_payment_icon_base64("mastercard.png"),
      color: "#EB001B",
    ),
  }.freeze
  DEFAULT_INSTITUTION = Suma::Payment::Institution.new(
    name: "",
    logo: self.load_payment_icon_base64("default.png"),
    color: "#AAAAAA",
  )
end

# Table: payment_cards
# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id              | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at      | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at      | timestamp with time zone |
#  soft_deleted_at | timestamp with time zone |
#  legal_entity_id | integer                  | NOT NULL
#  stripe_json     | jsonb                    | NOT NULL
# Indexes:
#  payment_cards_pkey                  | PRIMARY KEY btree (id)
#  payment_cards_legal_entity_id_index | btree (legal_entity_id)
# Foreign key constraints:
#  payment_cards_legal_entity_id_fkey | (legal_entity_id) REFERENCES legal_entities(id) ON DELETE RESTRICT
# Referenced By:
#  commerce_checkouts                                 | commerce_checkouts_card_id_fkey                                 | (card_id) REFERENCES payment_cards(id)
#  payment_funding_transaction_stripe_card_strategies | payment_funding_transaction_stripe_car_originating_card_id_fkey | (originating_card_id) REFERENCES payment_cards(id)
# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------
