# frozen_string_literal: true

require "suma/payment/funding_transaction/strategy"
require "suma/payment/payout_transaction/strategy"
require "suma/postgres/model"

class Suma::Payment::OffPlatformStrategy < Suma::Postgres::Model(:payment_off_platform_strategies)
  include Suma::AdminLinked
  include Suma::Payment::FundingTransaction::Strategy
  include Suma::Payment::PayoutTransaction::Strategy

  one_to_one :funding_transaction, class: "Suma::Payment::FundingTransaction"
  one_to_one :payout_transaction, class: "Suma::Payment::PayoutTransaction"
  many_to_one :created_by, class: "Suma::Member"
  many_to_one :organization, class: "Suma::Organization"
  many_to_one :vendor, class: "Suma::Vendor"

  def transaction = self.funding_transaction || self.payout_transaction
  def type = self.funding_transaction ? "Funding" : "Payout"

  def short_name = "Off Platform Payment"
  def originating_instrument_label = "Off Platform"
  def check_validity = []

  def admin_details
    return {
      "Transacted At" => self.transacted_at,
      "Created By" => self.created_by&.name,
      "Check/Transaction" => self.check_or_transaction_number,
      "Note" => self.note,
      "Organization" => self.organization,
      "Vendor" => self.vendor,
    }
  end

  def ready_to_collect_funds? = true
  def collect_funds = nil
  def funds_cleared? = true
  def funds_canceled? = false

  def ready_to_send_funds? = true
  def send_funds = nil
  def funds_settled? = true
  def send_failed? = false

  def rel_admin_link = "/payment-off-platform/#{self.id}"

  def before_save
    [:note, :check_or_transaction_number].each do |f|
      self[f] = self[f].strip if self[f]
    end
    self[:check_or_transaction_number] = nil if self[:check_or_transaction_number].blank?
    super
  end
end

# Table: payment_off_platform_strategies
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                          | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at                  | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at                  | timestamp with time zone |
#  created_by_id               | integer                  |
#  note                        | text                     | NOT NULL
#  check_or_transaction_number | text                     |
#  transacted_at               | timestamp with time zone | NOT NULL
#  vendor_id                   | integer                  |
#  organization_id             | integer                  |
# Indexes:
#  payment_off_platform_strategies_pkey                            | PRIMARY KEY btree (id)
#  payment_off_platform_strategies_check_or_transaction_number_ind | btree (check_or_transaction_number)
# Check constraints:
#  null_or_present_number | (check_or_transaction_number IS NULL OR check_or_transaction_number <> ''::text)
# Foreign key constraints:
#  payment_off_platform_strategies_created_by_id_fkey   | (created_by_id) REFERENCES members(id)
#  payment_off_platform_strategies_organization_id_fkey | (organization_id) REFERENCES organizations(id)
#  payment_off_platform_strategies_vendor_id_fkey       | (vendor_id) REFERENCES vendors(id)
# Referenced By:
#  payment_funding_transactions | payment_funding_transactions_off_platform_strategy_id_fkey | (off_platform_strategy_id) REFERENCES payment_off_platform_strategies(id)
#  payment_payout_transactions  | payment_payout_transactions_off_platform_strategy_id_fkey  | (off_platform_strategy_id) REFERENCES payment_off_platform_strategies(id)
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
