services:
  db:
    image: "postgres:16"
    ports:
      - "22005:5432"
    environment:
      POSTGRES_USER: 'suma'
      POSTGRES_PASSWORD: 'suma'
      POSTGRES_DB: 'suma'
  test_db:
    build:
      context: .
      dockerfile: ./docker/pg.Dockerfile
    ports:
      - "22006:5432"
    environment:
      POSTGRES_USER: 'suma'
      POSTGRES_PASSWORD: 'suma'
      POSTGRES_DB: 'suma_test'
  sidekiq_redis:
    image: "redis:7"
    ports:
      - "22007:6379"
