# frozen_string_literal: true

source "https://rubygems.org"
ruby "3.3.7"

gem "activesupport", "~> 7.2"
gem "appydays", git: 'https://github.com/lithictech/appydays.git', branch: "sidekiq8"
gem "base64"
gem "bcrypt"
gem "biz"
gem "browser"
gem "foreman"
gem "frontapp"
gem "geokit"
gem "grape", "~> 2.4"
gem "grape-entity", "~> 1.0"
gem "grape_logging"
gem "grape-swagger"
gem "holidays"
gem "httparty", "~> 0.22"
gem "image_processing", "~> 1.0"
gem "liquid"
gem "mimemagic"
gem "monetize"
gem "money"
gem "nokogiri", "~> 1.18"
gem "parser"
gem "pg"
gem "pgvector"
gem "phony"
gem "platform-api"
gem "premailer"
gem "pry"
gem "pry-clipboard2"
gem "puma", "~> 6.6"
gem "rack", "~> 3.1"
gem "rack-attack"
gem "rack-cors", "~> 2.0"
gem "rack-protection"
gem "rack-session", '~> 2.1'
gem "rack-ssl-enforcer"
gem "rake"
gem "redcarpet"
gem "redis"
gem "redis-client"
gem "ruby-vips"
gem "semantic_logger"
gem "sentry-ruby"
gem "sentry-sidekiq"
gem "sequel", ">= 5.75"
gem "sequel-annotate"
gem "sequel-money-fields"
gem "sequel_pg"
gem "sequel-soft-deletes"
gem "sequel-state-machine", "~> 1.4"
gem "sequel-tstzrange-fields"
gem "sidekiq", "~> 8.0"
gem "sidekiq-amigo", git: 'https://github.com/lithictech/sidekiq-amigo.git', branch: "sidekiq8"
gem "sidekiq-cron"
gem "sidekiq-unique-jobs", "~> 8.0"
gem "signalwire"
gem "smstools"
gem "state_machines"
gem "stripe"
gem "twilio-ruby", "~> 5.74"
gem "yajl-ruby"

# By default, Heroku ignores 'test' gem groups.
# But for ci, we need these gems loaded. It doesn't appear possible to 'fool' heroku using BUNDLE_WITHOUT
# to only exclude some fake group.
# So we include this test group by default, then BUNDLE_WITHOUT the real apps.
group :test_group do
  gem "amazing_print"
  gem "bundle-audit"
  gem "clipboard"
  gem "faker"
  gem "fluent_fixtures"
  gem "rack-test"
  gem "rspec"
  gem "rspec-eventually"
  gem "rspec-json_expectations"
  gem "rspec-temp_dir"
  gem "rubocop", "~> 1.65.1"
  gem "rubocop-performance", require: false
  gem "rubocop-rake", require: false
  gem "rubocop-sequel", require: false
  gem "simplecov", require: false
  gem "simplecov-cobertura"
  gem "timecop"
  gem "webmock", "~> 3.23"
end
