# frozen_string_literal: true

source "https://rubygems.org"
ruby "3.1.2"

gem "activesupport"
gem "appydays", "~> 0.7"
gem "bcrypt"
gem "biz"
gem "browser"
gem "foreman"
gem "frontapp"
gem "geokit"
gem "grape"
gem "grape-entity"
gem "grape_logging"
gem "grape-swagger"
gem "holidays"
gem "httparty"
gem "image_processing", "~> 1.0"
gem "liquid"
gem "mimemagic"
gem "monetize"
gem "money"
gem "name_of_person"
gem "nokogiri"
gem "parser"
gem "pg"
gem "phony"
gem "platform-api"
gem "premailer"
gem "pry"
gem "pry-clipboard2"
gem "puma"
gem "rack-cors"
gem "rack-protection"
gem "rack-ssl-enforcer"
gem "rake"
gem "redis-client"
gem "ruby-vips"
gem "semantic_logger"
gem "sentry-ruby"
gem "sentry-sidekiq"
gem "sequel", ">= 5.75"
gem "sequel-annotate"
gem "sequel-money-fields"
gem "sequel_pg"
gem "sequel-soft-deletes"
gem "sequel-state-machine", "~> 1.4"
gem "sequel-tstzrange-fields"
gem "sidekiq"
gem "sidekiq-amigo", ">= 1.7.0"
gem "sidekiq-cron"
gem "sidekiq-unique-jobs"
gem "signalwire"
gem "state_machines"
gem "stripe"
gem "twilio-ruby", "~> 5.74"
gem "warden"
gem "yajl-ruby"

# By default, Heroku ignores 'test' gem groups.
# But for ci, we need these gems loaded. It doesn't appear possible to 'fool' heroku using BUNDLE_WITHOUT
# to only exclude some fake group.
# So we include this test group by default, then BUNDLE_WITHOUT the real apps.
group :test_group do
  gem "amazing_print"
  gem "clipboard"
  gem "faker"
  gem "fluent_fixtures"
  gem "rack-test"
  gem "rspec"
  gem "rspec-eventually"
  gem "rspec-json_expectations"
  gem "rspec-temp_dir"
  gem "rubocop", "~> 1.31.1"
  gem "rubocop-performance", require: false
  gem "rubocop-rake", require: false
  gem "rubocop-sequel", require: false
  gem "simplecov", require: false
  gem "simplecov-cobertura"
  gem "timecop"
  gem "webmock"
end
