# frozen_string_literal: true

require "suma/analytics/model"

class Suma::Analytics::Charge < Suma::Analytics::Model(Sequel[:analytics][:charges])
  unique_key :charge_id

  destroy_from Suma::Charge

  denormalize Suma::Charge, with: :denormalize_charge

  def self.denormalize_charge(charge)
    # one or the other must be set
    incurred_at = charge.mobility_trip&.ended_at || charge.commerce_order.created_at
    return {
      charge_id: charge.id,
      opaque_id: charge.opaque_id,
      created_at: charge.created_at,
      member_id: charge.member_id,
      order_id: charge.commerce_order_id,
      trip_id: charge.mobility_trip_id,
      incurred_at:,
      undiscounted_subtotal: charge.undiscounted_subtotal,
      discounted_subtotal: charge.discounted_subtotal,
      discount_amount: charge.discount_amount,
      cash_paid: charge.cash_paid_from_ledger,
      noncash_paid: charge.noncash_paid_from_ledger,
    }
  end
end

# Table: analytics.charges
# ------------------------------------------------------------------------------------------------
# Columns:
#  pk                    | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  charge_id             | integer                  | NOT NULL
#  created_at            | timestamp with time zone |
#  opaque_id             | text                     |
#  member_id             | integer                  |
#  order_id              | integer                  |
#  trip_id               | integer                  |
#  discounted_subtotal   | numeric                  |
#  discount_amount       | numeric                  |
#  undiscounted_subtotal | numeric                  |
#  cash_paid             | numeric                  |
#  noncash_paid          | numeric                  |
# Indexes:
#  charges_pkey          | PRIMARY KEY btree (pk)
#  charges_charge_id_key | UNIQUE btree (charge_id)
# ------------------------------------------------------------------------------------------------
