# frozen_string_literal: true

require "suma/analytics/model"

class Suma::Analytics::Charge < Suma::Analytics::Model(Sequel[:analytics][:charges])
  unique_key :charge_id

  destroy_from Suma::Charge

  denormalize Suma::Charge, with: [
    [:charge_id, :id],
    :opaque_id,
    :created_at,
    :member_id,
    [:order_id, :commerce_order_id],
    [:trip_id, :mobility_trip_id],
    :undiscounted_subtotal,
    :discounted_subtotal,
    :discount_amount,
    [:cash_paid, [:commerce_order, :cash_paid_from_ledger]],
    [:noncash_paid, [:commerce_order, :noncash_paid_from_ledger]],
  ]
end

# Table: analytics.charges
# ------------------------------------------------------------------------------------------------
# Columns:
#  pk                    | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  charge_id             | integer                  | NOT NULL
#  created_at            | timestamp with time zone |
#  opaque_id             | text                     |
#  member_id             | integer                  |
#  order_id              | integer                  |
#  trip_id               | integer                  |
#  discounted_subtotal   | numeric                  |
#  discount_amount       | numeric                  |
#  undiscounted_subtotal | numeric                  |
#  cash_paid             | numeric                  |
#  noncash_paid          | numeric                  |
# Indexes:
#  charges_pkey          | PRIMARY KEY btree (pk)
#  charges_charge_id_key | UNIQUE btree (charge_id)
# ------------------------------------------------------------------------------------------------
