# frozen_string_literal: true

require "suma/analytics/model"

class Suma::Analytics::OrderItem < Suma::Analytics::Model(Sequel[:analytics][:order_items])
  unique_key :checkout_item_id

  destroy_from Suma::Commerce::CheckoutItem

  denormalize Suma::Commerce::Order, with: :denormalize_order

  def self.denormalize_order(order)
    checkout = order.checkout
    member = checkout.cart.member
    return order.checkout.items.map do |ci|
      {
        checkout_item_id: ci.id,
        created_at: order.created_at,
        order_id: order.id,
        member_id: member.id,
        quantity: ci.quantity,
        undiscounted_cost: ci.undiscounted_cost,
        customer_cost: ci.customer_cost,
        savings: ci.savings,
        product_id: ci.offering_product.product_id,
        product_name: ci.offering_product.product.name.en,
        vendor_id: ci.offering_product.product.vendor_id,
        vendor_name: ci.offering_product.product.vendor.name,
        offering_id: ci.checkout.cart.offering_id,
        offering_name: ci.checkout.cart.offering.description.en,
        offering_begin: ci.checkout.cart.offering.period.begin,
        offering_end: ci.checkout.cart.offering.period.end,
      }
    end
  end
end

# Table: analytics.order_items
# --------------------------------------------------------------------------------------------
# Columns:
#  pk                | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  checkout_item_id  | integer                  | NOT NULL
#  created_at        | timestamp with time zone |
#  order_id          | integer                  |
#  member_id         | integer                  |
#  undiscounted_cost | numeric                  |
#  customer_cost     | numeric                  |
#  savings           | numeric                  |
# Indexes:
#  order_items_pkey                 | PRIMARY KEY btree (pk)
#  order_items_checkout_item_id_key | UNIQUE btree (checkout_item_id)
# --------------------------------------------------------------------------------------------
