# frozen_string_literal: true

require "suma/analytics/model"

class Suma::Analytics::Trip < Suma::Analytics::Model(Sequel[:analytics][:trips])
  unique_key :trip_id

  destroy_from Suma::Mobility::Trip
  denormalize Suma::Mobility::Trip, with: [
    [:trip_id, :id],
    :created_at,

    :member_id,
    :vendor_service_id,
    [:vendor_service_name, [:vendor_service, :internal_name]],
    [:vendor_id, [:vendor_service, :vendor_id]],
    [:vendor_name, [:vendor_service, :vendor, :name]],
    :vendor_service_rate_id,
    [:vendor_service_rate_name, [:vendor_service_rate, :internal_name]],

    :began_at,
    :begin_lat,
    :begin_lng,
    :ended_at,
    :end_lat,
    :end_lng,

    [:undiscounted_cost, [:charge, :undiscounted_cost]],
    [:customer_cost, [:charge, :customer_cost]],
    [:savings, [:charge, :savings]],
    :our_cost,

    [:funded_cost, [:charge, :funded_amount]],
    [:cash_paid, [:charge, :cash_paid_from_ledger]],
    [:noncash_paid, [:charge, :noncash_paid_from_ledger]],
    [:paid_off_platform, [:charge, :off_platform_amount]],
  ]
end

# Table: analytics.trips
# ---------------------------------------------------------------------------------------------------
# Columns:
#  pk                       | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  trip_id                  | integer                  | NOT NULL
#  created_at               | timestamp with time zone |
#  member_id                | integer                  |
#  vendor_service_id        | integer                  |
#  vendor_service_name      | text                     |
#  vendor_id                | integer                  |
#  vendor_name              | text                     |
#  vendor_service_rate_id   | integer                  |
#  vendor_service_rate_name | text                     |
#  began_at                 | timestamp with time zone |
#  begin_lat                | numeric                  |
#  begin_lng                | numeric                  |
#  ended_at                 | timestamp with time zone |
#  end_lat                  | numeric                  |
#  end_lng                  | numeric                  |
#  undiscounted_cost        | numeric                  |
#  customer_cost            | numeric                  |
#  savings                  | numeric                  |
#  total                    | numeric                  |
#  funded_cost              | numeric                  |
#  cash_paid                | numeric                  |
#  noncash_paid             | numeric                  |
#  paid_off_platform        | numeric                  |
#  our_cost                 | numeric                  |
# Indexes:
#  trips_pkey        | PRIMARY KEY btree (pk)
#  trips_trip_id_key | UNIQUE btree (trip_id)
# ---------------------------------------------------------------------------------------------------
