# frozen_string_literal: true

require "suma/eligibility"
require "suma/postgres/model"

class Suma::Eligibility::Assignment < Suma::Postgres::Model(:eligibility_assignments)
  include Suma::AdminLinked
  include Suma::Postgres::HybridSearch

  plugin :hybrid_search
  plugin :timestamps

  many_to_one :attribute, class: "Suma::Eligibility::Attribute"

  many_to_one :created_by, class: "Suma::Member"

  many_to_one :member, class: "Suma::Member"
  many_to_one :organization, class: "Suma::Organization"
  many_to_one :role, class: "Suma::Role"

  ASSIGNEE_ASSOCIATIONS = [:member, :organization, :role].freeze

  def assignee = self.unambiguous_association(ASSIGNEE_ASSOCIATIONS)

  def assignee=(o)
    self.set_ambiguous_association(ASSIGNEE_ASSOCIATIONS, o)
  end

  def assignee_type = self.unambiguous_association_name(ASSIGNEE_ASSOCIATIONS)

  def assignee_label
    a = self.assignee
    return a.name.titleize if a.is_a?(Suma::Role)
    return a.name
  end

  def rel_admin_link = "/eligibility-assignment/#{self.id}"

  def hybrid_search_fields
    return [
      :attribute,
      :member,
      :organization,
      :role,
    ]
  end

  def before_create
    self.created_by = Suma.request_user_and_admin[1]
    super
  end
end

# Table: eligibility_assignments
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id               | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at       | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at       | timestamp with time zone |
#  created_by_id    | integer                  |
#  attribute_id     | integer                  | NOT NULL
#  member_id        | integer                  |
#  organization_id  | integer                  |
#  role_id          | integer                  |
#  search_content   | text                     |
#  search_embedding | vector(384)              |
#  search_hash      | text                     |
# Indexes:
#  eligibility_assignments_pkey                               | PRIMARY KEY btree (id)
#  eligibility_assignments_attribute_id_member_id_index       | UNIQUE btree (attribute_id, member_id) WHERE member_id IS NOT NULL
#  eligibility_assignments_attribute_id_organization_id_index | UNIQUE btree (attribute_id, organization_id) WHERE member_id IS NOT NULL
#  eligibility_assignments_attribute_id_role_id_index         | UNIQUE btree (attribute_id, role_id) WHERE member_id IS NOT NULL
#  eligibility_assignments_attribute_id_index                 | btree (attribute_id)
#  eligibility_assignments_search_content_tsvector_index      | gin (to_tsvector('english'::regconfig, search_content))
# Check constraints:
#  unambiguous_assignee | (member_id IS NOT NULL AND organization_id IS NULL AND role_id IS NULL OR member_id IS NULL AND organization_id IS NOT NULL AND role_id IS NULL OR member_id IS NULL AND organization_id IS NULL AND role_id IS NOT NULL)
# Foreign key constraints:
#  eligibility_assignments_attribute_id_fkey    | (attribute_id) REFERENCES eligibility_attributes(id) ON DELETE CASCADE
#  eligibility_assignments_created_by_id_fkey   | (created_by_id) REFERENCES members(id) ON DELETE SET NULL
#  eligibility_assignments_member_id_fkey       | (member_id) REFERENCES members(id) ON DELETE CASCADE
#  eligibility_assignments_organization_id_fkey | (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
#  eligibility_assignments_role_id_fkey         | (role_id) REFERENCES roles(id) ON DELETE CASCADE
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
