# frozen_string_literal: true

require "suma/eligibility"
require "suma/has_activity_audit"
require "suma/postgres/model"

class Suma::Eligibility::Attribute < Suma::Postgres::Model(:eligibility_attributes)
  include Suma::AdminLinked
  include Suma::HasActivityAudit
  include Suma::Postgres::HybridSearch

  plugin :hybrid_search
  plugin :timestamps

  many_to_one :parent, class: self
  one_to_many :children, class: self, key: :parent_id
  one_to_many :assignments, class: "Suma::Eligibility::Assignment"
  one_to_many :referenced_requirements,
              class: "Suma::Eligibility::Requirement",
              dataset: lambda {
                Suma::Eligibility::Requirement.where(Sequel.pg_array(:cached_attribute_ids).contains([id]))
              },
              skip_index_check: true,
              eager_loader: (lambda do |eo|
                id_map = {}
                eo[:rows].each do |parent|
                  parent.associations[:referenced_requirements] = []
                  id_map[parent.id] = parent
                end

                ds = Suma::Eligibility::Requirement.
                  where(Sequel.pg_array(:cached_attribute_ids).overlaps(id_map.keys))
                ds.all do |child|
                  child.cached_attribute_ids.each do |parent_id|
                    if (parent = id_map[parent_id])
                      parent.associations[:referenced_requirements] << child
                    end
                  end
                end
              end)

  class << self
    # Given a collection of attributes, accumulate all parents.
    # @return [Sequel::IdentitySet,Set<Suma::Eligibility::Attribute>]
    def accumulate(attrs, accum: Sequel::IdentitySet.new)
      attrs.each do |a|
        accum << a
        self.accumulate([a.parent], accum:) if a.parent
      end
      return accum
    end
  end

  def fqn_label
    return self.name if self.parent.nil?
    return "#{self.name}.#{self.parent.fqn_label}"
  end

  alias admin_label fqn_label

  def rel_admin_link = "/eligibility-attribute/#{self.id}"

  def hybrid_search_fields
    return [
      :name,
      :description,
      :parent,
    ]
  end
end

# Table: eligibility_attributes
# ---------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id               | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at       | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at       | timestamp with time zone |
#  name             | text                     | NOT NULL
#  description      | text                     | NOT NULL DEFAULT ''::text
#  parent_id        | integer                  |
#  search_content   | text                     |
#  search_embedding | vector(384)              |
#  search_hash      | text                     |
# Indexes:
#  eligibility_attributes_pkey                          | PRIMARY KEY btree (id)
#  eligibility_attributes_name_key                      | UNIQUE btree (name)
#  eligibility_attributes_parent_id_index               | btree (parent_id)
#  eligibility_attributes_search_content_tsvector_index | gin (to_tsvector('english'::regconfig, search_content))
# Check constraints:
#  no_self_reference | (parent_id IS NULL OR parent_id <> id)
# Foreign key constraints:
#  eligibility_attributes_parent_id_fkey | (parent_id) REFERENCES eligibility_attributes(id)
# Referenced By:
#  eligibility_assignments | eligibility_assignments_attribute_id_fkey | (attribute_id) REFERENCES eligibility_attributes(id) ON DELETE CASCADE
#  eligibility_attributes  | eligibility_attributes_parent_id_fkey     | (parent_id) REFERENCES eligibility_attributes(id)
#  eligibility_expressions | eligibility_expressions_attribute_id_fkey | (attribute_id) REFERENCES eligibility_attributes(id) ON DELETE CASCADE
# ---------------------------------------------------------------------------------------------------------------------------------------------
