# frozen_string_literal: true

require "suma/postgres/model"
require "suma/admin_linked"
require "suma/eligibility"

class Suma::Eligibility::Constraint < Suma::Postgres::Model(:eligibility_constraints)
  include Suma::AdminLinked

  STATUSES = ["pending", "verified", "rejected"].freeze

  plugin :timestamps

  many_to_many :offerings, class: "Suma::Commerce::Offering", join_table: :eligibility_offering_associations
  many_to_many :services, class: "Suma::Vendor::Service", join_table: :eligibility_vendor_service_associations
  many_to_many :configurations, class: "Suma::AnonProxy::VendorConfiguration",
                                join_table: :eligibility_anon_proxy_vendor_configuration_associations

  def self.assign_to_admins
    ec = self.all
    admins = Suma::Member.where(roles: Suma::Role.admin_role)
    admins.each do |m|
      ec.each do |e|
        m.replace_eligibility_constraint(e, "verified")
      end
    end
  end

  def rel_admin_link = "/constraint/#{self.id}"
end

# Table: eligibility_constraints
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id         | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at | timestamp with time zone |
#  name       | text                     | NOT NULL
# Indexes:
#  eligibility_constraints_pkey | PRIMARY KEY btree (id)
# Referenced By:
#  eligibility_anon_proxy_vendor_configuration_associations | eligibility_anon_proxy_vendor_configuration__constraint_id_fkey | (constraint_id) REFERENCES eligibility_constraints(id)
#  eligibility_member_associations                          | eligibility_member_associations_constraint_id_fkey              | (constraint_id) REFERENCES eligibility_constraints(id)
#  eligibility_offering_associations                        | eligibility_offering_associations_constraint_id_fkey            | (constraint_id) REFERENCES eligibility_constraints(id)
#  eligibility_vendor_service_associations                  | eligibility_vendor_service_associations_constraint_id_fkey      | (constraint_id) REFERENCES eligibility_constraints(id)
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
