# frozen_string_literal: true

require "suma/postgres/model"

require "suma/eligibility"

class Suma::Eligibility::Constraint < Suma::Postgres::Model(:eligibility_constraints)
  STATUSES = ["pending", "verified", "rejected"].freeze

  plugin :timestamps
end

# Table: eligibility_constraints
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id         | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at | timestamp with time zone |
#  name       | text                     | NOT NULL
# Indexes:
#  eligibility_constraints_pkey | PRIMARY KEY btree (id)
# Referenced By:
#  eligibility_anon_proxy_vendor_configuration_associations | eligibility_anon_proxy_vendor_configuration__constraint_id_fkey | (constraint_id) REFERENCES eligibility_constraints(id)
#  eligibility_member_associations                          | eligibility_member_associations_constraint_id_fkey              | (constraint_id) REFERENCES eligibility_constraints(id)
#  eligibility_offering_associations                        | eligibility_offering_associations_constraint_id_fkey            | (constraint_id) REFERENCES eligibility_constraints(id)
#  eligibility_vendor_service_associations                  | eligibility_vendor_service_associations_constraint_id_fkey      | (constraint_id) REFERENCES eligibility_constraints(id)
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
