# frozen_string_literal: true

require "suma/eligibility"
require "suma/postgres/model"

class Suma::Eligibility::Expression < Suma::Postgres::Model(:eligibility_expressions)
  many_to_one :left, class: self
  many_to_one :right, class: self
  many_to_one :attribute, class: "Suma::Eligibility::Attribute"
  one_to_one :requirement, class: "Suma::Eligibility::Requirement"

  # Mixin for easy usage.
  module Constants
    ATTRIBUTE = "attribute"
    UNARY = "unary"
    BINARY = "binary"

    AND = "AND"
    OR = "OR"
    NOT = "NOT"

    BINARY_OPS = [AND, OR].freeze
    UNARY_OPS = [NOT].freeze
  end

  include Constants

  class << self
    include Constants

    # Create an empty expression. We need this when creating a default in some places.
    def create_empty = self.create(type: BINARY, operator: AND)
  end

  def binary? = self.type == BINARY
  def unary? = self.type == UNARY
  def attribute? = self.type == ATTRIBUTE
  def empty? = self.attribute.nil? && self.left.nil? && self.right.nil?

  # Return left and right subexpressions, if set.
  # @return [Array<Suma::Eligibility::Expression]
  def subexpressions = [self.left, self.right].compact

  # Return all attributes used in the expression, recursively.
  # @return [Sequel::IdentitySet<Suma::Eligibility::Attribute>]
  def referenced_attributes(accum: Sequel::IdentitySet.new)
    if self.attribute?
      accum << self.attribute
      return accum
    end
    self.subexpressions.each { |e| e.referenced_attributes(accum:) }
    return accum
  end

  def to_formula_str
    return "'#{self.attribute.name}'" if self.attribute?
    substrs = self.subexpressions.map(&:to_formula_str).reject(&:empty?)
    return "" if substrs.empty?
    return "(#{self.operator} #{substrs[0]})" if self.unary?
    return substrs[0] if substrs.size == 1
    return "(#{substrs[0]} #{self.operator} #{substrs[1]})"
  end

  # Return a serializable object representing the expression.
  # Can be deserialized using deserialize.
  # @return [Hash]
  def serialize = Serializer.serialize(self)

  def tokenize
    return [] if self.empty?
    return Tokenizer.tokenize(self.serialize)
  end
end

require "suma/eligibility/expression/serializer"
require "suma/eligibility/expression/tokenizer"

# Table: eligibility_expressions
# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id           | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  attribute_id | integer |
#  left_id      | integer |
#  right_id     | integer |
#  operator     | text    |
#  type         | text    | NOT NULL
# Indexes:
#  eligibility_expressions_pkey | PRIMARY KEY btree (id)
# Check constraints:
#  coherent_type | (
#    CASE
#        WHEN type = 'attribute'::text THEN attribute_id IS NOT NULL AND left_id IS NULL AND right_id IS NULL AND operator IS NULL
#        WHEN type = 'binary'::text THEN (operator = ANY (ARRAY['AND'::text, 'OR'::text])) AND attribute_id IS NULL
#        WHEN type = 'unary'::text THEN operator = 'NOT'::text AND attribute_id IS NULL AND right_id IS NULL
#        ELSE NULL::boolean
#    END)
#  valid_type    | (type = ANY (ARRAY['attribute'::text, 'binary'::text, 'unary'::text]))
# Foreign key constraints:
#  eligibility_expressions_attribute_id_fkey | (attribute_id) REFERENCES eligibility_attributes(id) ON DELETE CASCADE
#  eligibility_expressions_left_id_fkey      | (left_id) REFERENCES eligibility_expressions(id) ON DELETE CASCADE
#  eligibility_expressions_right_id_fkey     | (right_id) REFERENCES eligibility_expressions(id) ON DELETE CASCADE
# Referenced By:
#  eligibility_expressions  | eligibility_expressions_left_id_fkey        | (left_id) REFERENCES eligibility_expressions(id) ON DELETE CASCADE
#  eligibility_expressions  | eligibility_expressions_right_id_fkey       | (right_id) REFERENCES eligibility_expressions(id) ON DELETE CASCADE
#  eligibility_requirements | eligibility_requirements_expression_id_fkey | (expression_id) REFERENCES eligibility_expressions(id) ON DELETE RESTRICT
# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
