# frozen_string_literal: true

require "suma/organization"
require "suma/postgres/model"

class Suma::Organization::Membership::VerificationAuditLog <
  Suma::Postgres::Model(:organization_membership_verification_audit_logs)
  plugin :state_machine_audit_log

  many_to_one :verification, class: "Suma::Organization::Membership::Verification", key: :verification_id
  many_to_one :actor, class: "Suma::Member"
end

# Table: organization_membership_verification_audit_logs
# -----------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id              | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  at              | timestamp with time zone | NOT NULL
#  event           | text                     | NOT NULL
#  to_state        | text                     | NOT NULL
#  from_state      | text                     | NOT NULL
#  reason          | text                     | NOT NULL DEFAULT ''::text
#  messages        | jsonb                    | NOT NULL DEFAULT '[]'::jsonb
#  verification_id | integer                  | NOT NULL
#  actor_id        | integer                  |
# Indexes:
#  organization_membership_verification_audit_logs_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  organization_membership_verification_audit_logs_actor_id_fkey   | (actor_id) REFERENCES members(id) ON DELETE SET NULL
#  organization_membership_verification_audit_verification_id_fkey | (verification_id) REFERENCES organization_membership_verifications(id) ON DELETE CASCADE
# -----------------------------------------------------------------------------------------------------------------------------------------------------------
