# frozen_string_literal: true

require "suma/postgres/model"

class Suma::Payment::Trigger::Execution < Suma::Postgres::Model(:payment_trigger_executions)
  many_to_one :trigger, class: "Suma::Payment::Trigger"
  many_to_one :book_transaction, class: "Suma::Payment::BookTransaction"
end

# Table: payment_trigger_executions
# ---------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                  | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at          | timestamp with time zone | NOT NULL DEFAULT now()
#  book_transaction_id | integer                  | NOT NULL
#  trigger_id          | integer                  | NOT NULL
# Indexes:
#  payment_trigger_executions_pkey                               | PRIMARY KEY btree (id)
#  payment_trigger_executions_trigger_id_book_transaction_id_key | UNIQUE btree (trigger_id, book_transaction_id)
# Foreign key constraints:
#  payment_trigger_executions_book_transaction_id_fkey | (book_transaction_id) REFERENCES payment_book_transactions(id)
#  payment_trigger_executions_trigger_id_fkey          | (trigger_id) REFERENCES payment_triggers(id)
# ---------------------------------------------------------------------------------------------------------------------
