# frozen_string_literal: true

require "suma/admin_linked"
require "suma/postgres/model"

class Suma::Charge::LineItem < Suma::Postgres::Model(:charge_line_items)
  include Suma::AdminLinked

  plugin :timestamps
  plugin :money_fields, :amount
  plugin :translated_text, :memo, Suma::TranslatedText

  many_to_one :charge, class: "Suma::Charge"

  def initialize(*)
    super
    self.opaque_id ||= Suma::Secureid.new_opaque_id("chi")
  end

  def rel_admin_link = "/charge-line-item/#{self.id}"
end

# Table: charge_line_items
# ------------------------------------------------------------------------------------------
# Columns:
#  id              | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at      | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at      | timestamp with time zone |
#  opaque_id       | text                     | NOT NULL
#  charge_id       | integer                  | NOT NULL
#  amount_cents    | integer                  | NOT NULL
#  amount_currency | text                     | NOT NULL
#  memo_id         | integer                  | NOT NULL
# Indexes:
#  charge_line_items_pkey            | PRIMARY KEY btree (id)
#  charge_line_items_opaque_id_key   | UNIQUE btree (opaque_id)
#  charge_line_items_charge_id_index | btree (charge_id)
# Foreign key constraints:
#  charge_line_items_charge_id_fkey | (charge_id) REFERENCES charges(id) ON DELETE CASCADE
#  charge_line_items_memo_id_fkey   | (memo_id) REFERENCES translated_texts(id)
# ------------------------------------------------------------------------------------------
