# frozen_string_literal: true

require "suma/admin_linked"
require "suma/postgres/model"

class Suma::Charge::LineItemSelfData < Suma::Postgres::Model(:charge_line_item_self_datas)
  include Suma::AdminLinked

  plugin :money_fields, :amount
  plugin :translated_text, :memo, Suma::TranslatedText

  one_to_one :line_item, class: "Suma::Charge::LineItem"
end

# Table: charge_line_item_self_datas
# ---------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id              | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  amount_cents    | integer | NOT NULL
#  amount_currency | text    | NOT NULL
#  memo_id         | integer | NOT NULL
# Indexes:
#  charge_line_item_self_datas_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  charge_line_item_self_datas_memo_id_fkey | (memo_id) REFERENCES translated_texts(id)
# Referenced By:
#  charge_line_items | charge_line_items_self_data_id_fkey | (self_data_id) REFERENCES charge_line_item_self_datas(id) ON DELETE RESTRICT
# ---------------------------------------------------------------------------------------------------------------------------------------
