# frozen_string_literal: true

require "suma/postgres/model"
require "suma/support"

class Suma::Support::Ticket < Suma::Postgres::Model(:support_tickets)
  plugin :timestamps

  many_to_one :member, class: "Suma::Member"
  many_to_many :uploaded_files,
               class: "Suma::UploadedFile",
               join_table: :support_tickets_uploaded_files,
               left_key: :support_ticket_id,
               order: order_desc

  def sync_to_front
    return if self.front_id
    params = {
      type: "discussion",
      inbox_id: Suma::Frontapp.to_inbox_id(Suma::Frontapp.default_inbox_id),
      subject: self.subject,
      "comment[body]" => self.body,
    }
    self.uploaded_files.each_with_index do |uf, i|
      params["attachments[#{i}]"] = HTTP::FormData::Part.new(
        uf.blob_stream_unsafe.read, content_type: uf.content_type, filename: uf.filename,
      )
    end
    resp = Suma::Frontapp.client.create_conversation(params)
    self.update(front_id: resp.fetch("id"))
    return resp
  end
end

# Table: support_tickets
# --------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id          | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at  | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at  | timestamp with time zone |
#  sender_name | text                     | NOT NULL DEFAULT ''::text
#  sender_id   | integer                  |
#  subject     | text                     | NOT NULL
#  body        | text                     | NOT NULL
#  external_id | text                     |
#  front_id    | text                     |
# Indexes:
#  support_tickets_pkey            | PRIMARY KEY btree (id)
#  support_tickets_external_id_key | UNIQUE btree (external_id)
# Foreign key constraints:
#  support_tickets_sender_id_fkey | (sender_id) REFERENCES members(id) ON DELETE SET NULL
# Referenced By:
#  support_tickets_uploaded_files | support_tickets_uploaded_files_support_ticket_id_fkey | (support_ticket_id) REFERENCES support_tickets(id)
# --------------------------------------------------------------------------------------------------------------------------------------------
