# frozen_string_literal: true

require "suma/postgres"
require "suma/member"

class Suma::Member::Referral < Suma::Postgres::Model(:member_referrals)
  plugin :timestamps

  many_to_one :member, class: Suma::Member
end

# Table: member_referrals
# --------------------------------------------------------------------------------------
# Columns:
#  id         | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at | timestamp with time zone | NOT NULL DEFAULT now()
#  channel    | text                     | NOT NULL
#  event_name | text                     | NOT NULL DEFAULT ''::text
#  member_id  | integer                  | NOT NULL
# Indexes:
#  member_referral_pkey             | PRIMARY KEY btree (id)
#  member_referrals_member_id_index | UNIQUE btree (member_id)
# Foreign key constraints:
#  member_referral_member_id_fkey | (member_id) REFERENCES members(id) ON DELETE CASCADE
# --------------------------------------------------------------------------------------
