# frozen_string_literal: true

require "suma/postgres"
require "suma/member"

class Suma::Member::Referral < Suma::Postgres::Model(:member_referral)
  plugin :timestamps

  one_to_one :member, class: Suma::Member
end

# Table: member_referral
# --------------------------------------------------------------------------------------
# Columns:
#  id               | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at       | timestamp with time zone | NOT NULL DEFAULT now()
#  member_id        | integer                  | NOT NULL
#  channel          | text                     | NOT NULL DEFAULT ''::text
#  event_name       | text                     | NOT NULL DEFAULT ''::text
# --------------------------------------------------------------------------------------
