# frozen_string_literal: true

require "suma/postgres"
require "suma/anon_proxy"

class Suma::AnonProxy::VendorAccountMessage < Suma::Postgres::Model(:anon_proxy_vendor_account_messages)
  plugin :timestamps

  many_to_one :vendor_account, class: "Suma::AnonProxy::VendorAccount"
  many_to_one :outbound_delivery, class: "Suma::Message::Delivery"
end

# Table: anon_proxy_vendor_account_messages
# -----------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                   | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at           | timestamp with time zone | NOT NULL DEFAULT now()
#  message_id           | text                     | NOT NULL
#  message_from         | text                     | NOT NULL
#  message_to           | text                     | NOT NULL
#  message_content      | text                     | NOT NULL
#  message_timestamp    | timestamp with time zone | NOT NULL
#  relay_key            | text                     | NOT NULL
#  message_handler_key  | text                     | NOT NULL
#  vendor_account_id    | integer                  | NOT NULL
#  outbound_delivery_id | integer                  | NOT NULL
# Indexes:
#  anon_proxy_vendor_account_messages_pkey                     | PRIMARY KEY btree (id)
#  anon_proxy_vendor_account_messages_outbound_delivery_id_key | UNIQUE btree (outbound_delivery_id)
#  anon_proxy_vendor_account_messages_vendor_account_id_index  | btree (vendor_account_id)
# Foreign key constraints:
#  anon_proxy_vendor_account_messages_outbound_delivery_id_fkey | (outbound_delivery_id) REFERENCES message_deliveries(id)
#  anon_proxy_vendor_account_messages_vendor_account_id_fkey    | (vendor_account_id) REFERENCES anon_proxy_vendor_accounts(id) ON DELETE CASCADE
# -----------------------------------------------------------------------------------------------------------------------------------------------
