# frozen_string_literal: true

require "browser"

require "suma/mobility"
require "suma/postgres/model"

class Suma::Mobility::Vehicle < Suma::Postgres::Model(:mobility_vehicles)
  plugin :timestamps

  many_to_one :vendor_service, key: :vendor_service_id, class: "Suma::Vendor::Service"

  dataset_module do
    def search(min_lat:, min_lng:, max_lat:, max_lng:)
      return self.where { (lat >= min_lat) & (lat <= max_lat) & (lng >= min_lng) & (lng <= max_lng) }
    end
  end

  def api_identity
    return "#{self.lat}-#{self.lng}-#{self.vendor_service_id}-#{self.vehicle_type}"
  end

  def to_api_location
    return [self.lat_int, self.lng_int]
  end

  FALLBACK_DEEP_LINK_URL = "#{Suma.app_url}/error".freeze

  def deep_link_for_user_agent(user_agent)
    return nil unless self.vendor_service.mobility_adapter.uses_deep_linking?
    browser = Browser.new(user_agent || "", accept_language: "en-us")
    uris = self.rental_uris
    key = if browser.platform.android?
            "android"
    elsif browser.platform.ios?
      "ios"
    else
      "web"
    end
    key_preferences = [key, "web", "android", "ios"]
    key_preferences.each do |k|
      return uris[k] if uris[k]
    end
    Sentry.capture_message("Cannot find rental URIs for a user agent: #{user_agent}, #{uris}")
    return FALLBACK_DEEP_LINK_URL
  end

  def before_save
    self.lat_int = Suma::Mobility.coord2int(self.lat)
    self.lng_int = Suma::Mobility.coord2int(self.lng)
    super
  end
end

# Table: mobility_vehicles
# ----------------------------------------------------------------------------------------------------------------
# Columns:
#  id                | integer  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  lat               | numeric  | NOT NULL
#  lng               | numeric  | NOT NULL
#  vehicle_type      | text     | NOT NULL
#  vehicle_id        | text     | NOT NULL
#  vendor_service_id | integer  | NOT NULL
#  battery_level     | smallint |
#  rental_uris       | jsonb    | NOT NULL DEFAULT '{}'::jsonb
#  lat_int           | integer  | NOT NULL
#  lng_int           | integer  | NOT NULL
# Indexes:
#  mobility_vehicles_pkey                    | PRIMARY KEY btree (id)
#  mobility_vehicles_vendor_service_id_index | btree (vendor_service_id)
# Check constraints:
#  valid_battery_level | (battery_level >= 0 AND battery_level <= 100)
# Foreign key constraints:
#  mobility_vehicles_vendor_service_id_fkey | (vendor_service_id) REFERENCES vendor_services(id) ON DELETE CASCADE
# ----------------------------------------------------------------------------------------------------------------
