# frozen_string_literal: true

require "suma/postgres/model"

# Represents dynamic credentials used to access some external system.
# Usually this would be something like an oauth token.
class Suma::ExternalCredential < Suma::Postgres::Model(:external_credentials)
  plugin :insert_conflict
  plugin :column_encryption do |enc|
    enc.column :data
  end
end

# Table: external_credentials
# -------------------------------------------------------------------------------------
# Columns:
#  id         | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  service    | text                     | NOT NULL
#  expires_at | timestamp with time zone |
#  data       | text                     | NOT NULL
# Indexes:
#  external_credentials_pkey        | PRIMARY KEY btree (id)
#  external_credentials_service_key | UNIQUE btree (service)
# -------------------------------------------------------------------------------------
