# frozen_string_literal: true

require "suma/postgres/model"

class Suma::LegalEntity < Suma::Postgres::Model(:legal_entities)
  many_to_one :address, class: "Suma::Address"
  one_to_one :customer, class: "Suma::Customer"
end

# Table: legal_entities
# -----------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id              | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at      | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at      | timestamp with time zone |
#  soft_deleted_at | timestamp with time zone |
#  name            | text                     | NOT NULL DEFAULT ''::text
#  address_id      | integer                  |
# Indexes:
#  legal_entities_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  legal_entities_address_id_fkey | (address_id) REFERENCES addresses(id) ON DELETE SET NULL
# Referenced By:
#  customer_linked_legal_entities | customer_linked_legal_entities_linked_legal_entity_id_fkey | (linked_legal_entity_id) REFERENCES legal_entities(id)
#  customers                      | customers_legal_entity_id_fkey                             | (legal_entity_id) REFERENCES legal_entities(id)
# -----------------------------------------------------------------------------------------------------------------------------------------------------
