# frozen_string_literal: true

require "suma/postgres/model"

class Suma::Market < Suma::Postgres::Model(:markets)
  plugin :timestamps

  def before_create
    self.slug ||= Suma.to_slug(self.name)
  end
end

# Table: markets
# -------------------------------------------------------------------------------------
# Columns:
#  id         | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at | timestamp with time zone |
#  name       | text                     | NOT NULL
#  slug       | text                     | NOT NULL
# Indexes:
#  markets_pkey | PRIMARY KEY btree (id)
# -------------------------------------------------------------------------------------
