# frozen_string_literal: true

require "suma/postgres/model"
require "suma/admin_linked"
require "suma/role"

class Suma::Organization < Suma::Postgres::Model(:organizations)
  include Suma::Postgres::HybridSearch
  include Suma::AdminLinked
  include Suma::HasActivityAudit

  plugin :association_pks
  plugin :hybrid_search
  plugin :timestamps
  # This is not actually localized text, it points to localized template IDs.
  plugin :translated_text, :membership_verification_member_outreach_template, Suma::TranslatedText

  one_to_many :memberships,
              class: "Suma::Organization::Membership",
              key: :verified_organization_id,
              order: order_desc
  one_to_many :former_memberships,
              class: "Suma::Organization::Membership",
              key: :former_organization_id,
              order: order_desc
  one_to_many :program_enrollments, class: "Suma::Program::Enrollment", order: order_desc
  many_to_many :roles,
               class: "Suma::Role",
               join_table: :roles_organizations,
               order: order_assoc(:asc, :name),
               **Suma::Role.association_options

  plugin :association_array_replacer, :roles

  def rel_admin_link = "/organization/#{self.id}"

  def hybrid_search_fields
    return [
      :name,
    ]
  end
end

# Table: organizations
# --------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                                                  | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at                                          | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at                                          | timestamp with time zone |
#  name                                                | text                     | NOT NULL
#  search_content                                      | text                     |
#  search_embedding                                    | vector(384)              |
#  search_hash                                         | text                     |
#  ordinal                                             | double precision         | NOT NULL DEFAULT 0
#  membership_verification_email                       | text                     | NOT NULL DEFAULT ''::text
#  membership_verification_front_template_id           | text                     | NOT NULL DEFAULT ''::text
#  membership_verification_member_outreach_template_id | integer                  |
# Indexes:
#  organizations_pkey                          | PRIMARY KEY btree (id)
#  organizations_name_key                      | UNIQUE btree (name)
#  organizations_search_content_tsvector_index | gin (to_tsvector('english'::regconfig, search_content))
# Foreign key constraints:
#  organizations_membership_verification_member_outreach_temp_fkey | (membership_verification_member_outreach_template_id) REFERENCES translated_texts(id)
# Referenced By:
#  organization_memberships | organization_memberships_former_organization_id_fkey   | (former_organization_id) REFERENCES organizations(id)
#  organization_memberships | organization_memberships_verified_organization_id_fkey | (verified_organization_id) REFERENCES organizations(id)
#  program_enrollments      | program_enrollments_organization_id_fkey               | (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
#  roles_organizations      | roles_organizations_organization_id_fkey               | (organization_id) REFERENCES organizations(id)
# --------------------------------------------------------------------------------------------------------------------------------------------------------
