# frozen_string_literal: true

require "suma/http"
require "suma/plaid"
require "suma/postgres/model"

class Suma::PlaidInstitution < Suma::Postgres::Model(:plaid_institutions)
  plugin :timestamps

  def self.update_all
    offset = 0
    loop do
      resp = Suma::Http.post(
        Suma::Plaid.host + "/institutions/get",
        {
          client_id: Suma::Plaid.client_id,
          secret: Suma::Plaid.secret,
          count: 50,
          offset:,
          country_codes: Suma::Plaid.supported_country_codes,
          options: {include_optional_metadata: true},
        },
        logger: self.logger,
      )
      return if resp.parsed_response["institutions"].blank?
      resp.parsed_response["institutions"].each do |inst|
        Suma::PlaidInstitution.update_or_create(
          {institution_id: inst["institution_id"]},
          {
            name: inst["name"],
            logo_base64: inst["logo"] || "",
            primary_color_hex: inst["primary_color"] || "#000000",
            routing_numbers: inst["routing_numbers"] || [],
            data: inst["to_json"] || "{}",
          },
        )
        sleep(Suma::Plaid.bulk_sync_sleep) if Suma::Plaid.bulk_sync_sleep
      end
      offset += 50
    end
  end
end

# Table: plaid_institutions
# ----------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  pk                | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at        | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at        | timestamp with time zone |
#  institution_id    | text                     | NOT NULL
#  name              | text                     | NOT NULL
#  logo_base64       | text                     | NOT NULL DEFAULT ''::text
#  primary_color_hex | text                     | NOT NULL DEFAULT '#000000'::text
#  routing_numbers   | text[]                   | NOT NULL
#  data              | jsonb                    | NOT NULL DEFAULT '{}'::jsonb
# Indexes:
#  plaid_institutions_pkey                  | PRIMARY KEY btree (pk)
#  plaid_institutions_institution_id_key    | UNIQUE btree (institution_id)
#  plaid_institutions_routing_numbers_index | gin (routing_numbers)
# Referenced By:
#  payment_bank_accounts | bank_accounts_plaid_institution_id_fkey | (plaid_institution_id) REFERENCES plaid_institutions(pk) ON DELETE SET NULL
# ----------------------------------------------------------------------------------------------------------------------------------------------
