# frozen_string_literal: true

require "suma/postgres/model"

class Suma::SupportedCurrency < Suma::Postgres::Model(:supported_currencies)
end

# Table: supported_currencies
# ----------------------------------------------------------------------------------------
# Columns:
#  id                    | integer          | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  symbol                | text             | NOT NULL
#  code                  | text             | NOT NULL
#  funding_minimum_cents | integer          | NOT NULL
#  funding_step_cents    | integer          | NOT NULL
#  cents_in_dollar       | integer          | NOT NULL
#  payment_method_types  | text[]           | NOT NULL
#  ordinal               | double precision | NOT NULL
# Indexes:
#  supported_currencies_pkey        | PRIMARY KEY btree (id)
#  supported_currencies_ordinal_key | UNIQUE btree (ordinal)
# ----------------------------------------------------------------------------------------
