# frozen_string_literal: true

require "sequel/sequel_translated_text"
require "suma/postgres/model"

class Suma::TranslatedText < Suma::Postgres::Model(:translated_texts)
  include SequelTranslatedText::Model

  class << self
    def empty
      return Suma.cached_get("translated_text_empty") do
        self.find_or_create(en: "", es: "")
      end
    end
  end

  dataset_module do
    # Return a dataset with a full_text_search on a supported lang column like :en or :es.
    def search(col, q)
      pglang = case col
        when :en
          "english"
        when :es
          "spanish"
        else
          raise ArgumentError, "invalid column name: #{col}"
      end
      return self.full_text_search(
        :"#{col}_tsvector",
        q,
        to_tsquery: :websearch,
        rank: true,
        language: pglang,
        tsvector: true,
      )
    end

    # Return a dataset limited to translations unique on the given column,
    # and then searched with full text search.
    def distinct_search(col, q)
      # Perform a subselect since otherwise we can't sort with distinct.
      all_unique = Suma::TranslatedText.dataset.distinct(col)
      return self.where(id: all_unique.select(:id)).search(col, q)
    end
  end

  # Return a new instance, with all string fields formatted with the given kwargs.
  # Formatting is done on simple replacements, like '{{ x }}' is replaced with an 'x' kwarg.
  # This is a subset of the behavior in `i18n.js` on the frontend,
  # as this does not work with functions or references.
  def format(**kwargs)
    en = self.en
    es = self.es
    kwargs.each do |k, v|
      en = en.gsub(/\{\{(\s*#{k}\s*)}}/) { v }
      es = es.gsub(/\{\{(\s*#{k}\s*)}}/) { v }
    end
    return self.class.new(en:, es:)
  end

  # Like +format+, but save the instance, or return an existing one with the same text.
  def format!(**)
    o2 = self.format(**)
    existing = self.class[en: o2.en, es: o2.es]
    return existing if existing
    return o2.save_changes
  end
end

# Table: translated_texts
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id          | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at  | timestamp with time zone | NOT NULL DEFAULT now()
#  en          | text                     | NOT NULL DEFAULT ''::text
#  es          | text                     | NOT NULL DEFAULT ''::text
#  en_tsvector | tsvector                 | NOT NULL DEFAULT to_tsvector('english'::regconfig, en)
#  es_tsvector | tsvector                 | NOT NULL DEFAULT to_tsvector('spanish'::regconfig, es)
# Indexes:
#  translated_texts_pkey | PRIMARY KEY btree (id)
#  en_tsvector_idx       | gin (en_tsvector)
#  es_tsvector_idx       | gin (es_tsvector)
# Referenced By:
#  anon_proxy_vendor_configurations      | anon_proxy_vendor_configurati_linked_success_instructions__fkey | (linked_success_instructions_id) REFERENCES translated_texts(id)
#  anon_proxy_vendor_configurations      | anon_proxy_vendor_configurations_instructions_id_fkey           | (instructions_id) REFERENCES translated_texts(id)
#  charge_line_items                     | charge_line_items_memo_id_fkey                                  | (memo_id) REFERENCES translated_texts(id)
#  commerce_offering_fulfillment_options | commerce_offering_fulfillment_options_description_id_fkey       | (description_id) REFERENCES translated_texts(id)
#  commerce_offerings                    | commerce_offerings_description_id_fkey                          | (description_id) REFERENCES translated_texts(id)
#  commerce_offerings                    | commerce_offerings_fulfillment_confirmation_id_fkey             | (fulfillment_confirmation_id) REFERENCES translated_texts(id)
#  commerce_offerings                    | commerce_offerings_fulfillment_instructions_id_fkey             | (fulfillment_instructions_id) REFERENCES translated_texts(id)
#  commerce_offerings                    | commerce_offerings_fulfillment_prompt_id_fkey                   | (fulfillment_prompt_id) REFERENCES translated_texts(id)
#  commerce_products                     | commerce_products_description_id_fkey                           | (description_id) REFERENCES translated_texts(id)
#  commerce_products                     | commerce_products_name_id_fkey                                  | (name_id) REFERENCES translated_texts(id)
#  i18n_static_strings                   | i18n_static_strings_text_id_fkey                                | (text_id) REFERENCES translated_texts(id) ON DELETE CASCADE
#  images                                | images_caption_id_fkey                                          | (caption_id) REFERENCES translated_texts(id)
#  marketing_sms_broadcasts              | marketing_sms_broadcasts_body_id_fkey                           | (body_id) REFERENCES translated_texts(id)
#  organizations                         | organizations_membership_verification_member_outreach_temp_fkey | (membership_verification_member_outreach_template_id) REFERENCES translated_texts(id)
#  payment_book_transactions             | payment_book_transactions_memo_id_fkey                          | (memo_id) REFERENCES translated_texts(id)
#  payment_funding_transactions          | payment_funding_transactions_memo_id_fkey                       | (memo_id) REFERENCES translated_texts(id)
#  payment_ledgers                       | payment_ledgers_contribution_text_id_fkey                       | (contribution_text_id) REFERENCES translated_texts(id)
#  payment_payout_transactions           | payment_payout_transactions_memo_id_fkey                        | (memo_id) REFERENCES translated_texts(id)
#  payment_triggers                      | payment_triggers_memo_id_fkey                                   | (memo_id) REFERENCES translated_texts(id)
#  payment_triggers                      | payment_triggers_receiving_ledger_contribution_text_id_fkey     | (receiving_ledger_contribution_text_id) REFERENCES translated_texts(id)
#  programs                              | programs_app_link_text_id_fkey                                  | (app_link_text_id) REFERENCES translated_texts(id)
#  programs                              | programs_description_id_fkey                                    | (description_id) REFERENCES translated_texts(id)
#  programs                              | programs_name_id_fkey                                           | (name_id) REFERENCES translated_texts(id)
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
