# frozen_string_literal: true

require "sequel/sequel_translated_text"
require "suma/postgres/model"

class Suma::TranslatedText < Suma::Postgres::Model(:translated_texts)
  include SequelTranslatedText::Model
end

# Table: translated_texts
# -----------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id         | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at | timestamp with time zone | NOT NULL DEFAULT now()
#  en         | text                     | NOT NULL DEFAULT ''::text
#  es         | text                     | NOT NULL DEFAULT ''::text
# Indexes:
#  translated_texts_pkey | PRIMARY KEY btree (id)
# Referenced By:
#  commerce_offering_fulfillment_options | commerce_offering_fulfillment_options_description_id_fkey | (description_id) REFERENCES translated_texts(id)
#  commerce_offerings                    | commerce_offerings_description_id_fkey                    | (description_id) REFERENCES translated_texts(id)
#  commerce_products                     | commerce_products_description_id_fkey                     | (description_id) REFERENCES translated_texts(id)
#  commerce_products                     | commerce_products_name_id_fkey                            | (name_id) REFERENCES translated_texts(id)
#  images                                | images_caption_id_fkey                                    | (caption_id) REFERENCES translated_texts(id)
# -----------------------------------------------------------------------------------------------------------------------------------------------------
