# frozen_string_literal: true

require "suma/admin_linked"
require "suma/image"
require "suma/postgres/model"

class Suma::Vendor < Suma::Postgres::Model(:vendors)
  include Suma::Postgres::HybridSearch
  include Suma::Image::SingleAssociatedMixin
  include Suma::AdminLinked

  plugin :hybrid_search
  plugin :timestamps

  one_to_one :payment_account, class: "Suma::Payment::Account"
  one_to_many :services, class: "Suma::Vendor::Service", order: order_desc
  one_to_many :configurations, class: "Suma::AnonProxy::VendorConfiguration", order: order_desc
  one_to_many :products, class: "Suma::Commerce::Product", order: order_desc

  def before_create
    self.slug ||= Suma.to_slug(self.name)
  end

  def after_create
    super
    self.payment_account ||= Suma::Payment::Account.create(vendor: self)
  end

  def rel_admin_link = "/vendor/#{self.id}"

  def hybrid_search_fields
    return [
      :name,
      :slug,
    ]
  end
end

# Table: vendors
# ------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id               | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at       | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at       | timestamp with time zone |
#  name             | text                     | NOT NULL
#  slug             | text                     | NOT NULL
#  search_content   | text                     |
#  search_embedding | vector(384)              |
#  search_hash      | text                     |
# Indexes:
#  vendors_pkey                          | PRIMARY KEY btree (id)
#  vendors_slug_index                    | UNIQUE btree (slug)
#  vendors_search_content_trigram_index  | gist (search_content)
#  vendors_search_content_tsvector_index | gin (to_tsvector('english'::regconfig, search_content))
# Referenced By:
#  anon_proxy_vendor_configurations | anon_proxy_vendor_configurations_vendor_id_fkey | (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
#  commerce_products                | commerce_products_vendor_id_fkey                | (vendor_id) REFERENCES vendors(id)
#  images                           | images_vendor_id_fkey                           | (vendor_id) REFERENCES vendors(id)
#  mobility_gbfs_feeds              | mobility_gbfs_feeds_vendor_id_fkey              | (vendor_id) REFERENCES vendors(id)
#  payment_accounts                 | payment_accounts_vendor_id_fkey                 | (vendor_id) REFERENCES vendors(id)
#  payment_off_platform_strategies  | payment_off_platform_strategies_vendor_id_fkey  | (vendor_id) REFERENCES vendors(id)
#  vendor_services                  | vendor_services_vendor_id_fkey                  | (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
# ------------------------------------------------------------------------------------------------------------------------------------------
