# frozen_string_literal: true

require "suma/admin_linked"
require "suma/image"
require "suma/postgres/model"

class Suma::Vendor < Suma::Postgres::Model(:vendors)
  include Suma::Image::SingleAssociatedMixin
  include Suma::AdminLinked

  plugin :timestamps

  one_to_one :payment_account, class: "Suma::Payment::Account"
  one_to_many :services, class: "Suma::Vendor::Service"
  one_to_many :configurations, class: "Suma::AnonProxy::VendorConfiguration"
  one_to_many :products, class: "Suma::Commerce::Product"

  def before_create
    self.slug ||= Suma.to_slug(self.name)
  end

  def after_create
    super
    self.payment_account ||= Suma::Payment::Account.create(vendor: self)
  end

  def rel_admin_link = "/vendor/#{self.id}"
end

# Table: vendors
# ------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id         | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at | timestamp with time zone |
#  name       | text                     | NOT NULL
#  slug       | text                     | NOT NULL
# Indexes:
#  vendors_pkey       | PRIMARY KEY btree (id)
#  vendors_slug_index | UNIQUE btree (slug)
# Referenced By:
#  anon_proxy_vendor_configurations | anon_proxy_vendor_configurations_vendor_id_fkey | (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
#  commerce_products                | commerce_products_vendor_id_fkey                | (vendor_id) REFERENCES vendors(id)
#  images                           | images_vendor_id_fkey                           | (vendor_id) REFERENCES vendors(id)
#  payment_accounts                 | payment_accounts_vendor_id_fkey                 | (vendor_id) REFERENCES vendors(id)
#  vendor_services                  | vendor_services_vendor_id_fkey                  | (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
# ------------------------------------------------------------------------------------------------------------------------------------------
