# frozen_string_literal: true

require "suma/postgres"
require "suma/customer"

class Suma::Member::Activity < Suma::Postgres::Model(:member_activities)
  plugin :timestamps

  many_to_one :member, class: Suma::Member
end

# Table: customer_journeys
# ---------------------------------------------------------------------------------------------------
# Columns:
#  id            | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at    | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at    | timestamp with time zone |
#  processed_at  | timestamp with time zone |
#  name          | text                     | NOT NULL
#  subject_type  | text                     | NOT NULL
#  subject_id    | text                     | NOT NULL
#  disambiguator | text                     | NOT NULL DEFAULT ''::text
#  message       | text                     | NOT NULL
#  customer_id   | integer                  | NOT NULL
# Indexes:
#  customer_journeys_pkey              | PRIMARY KEY btree (id)
#  customer_journeys_uniqueness_index  | UNIQUE btree (name, subject_type, subject_id, disambiguator)
#  customer_journeys_customer_id_index | btree (customer_id)
# Foreign key constraints:
#  customer_journeys_customer_id_fkey | (customer_id) REFERENCES customers(id) ON DELETE CASCADE
# ---------------------------------------------------------------------------------------------------
