name: PR Checks
on:
  pull_request:
  push: { branches: [main] }
jobs:
  backend-checks:
    # Match Heroku 22 stack
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 1
      - name: Update apt
        run: sudo apt-get update -yqq -o Acquire::Retries=3
      - name: Install dependencies
        run: sudo apt-get install --fix-missing -yqq -o Acquire::Retries=3 libvips libpq-dev
      - name: Start backing services
        run: docker-compose up -d
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Wait for services to come up
        run: sleep 0
      - name: Run specs
        env:
          RACK_ENV: test
        run: |
          bundle exec rake db:migrate
          bundle exec rspec spec/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: lithictech/suma
  webapp-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - run: npm install
      - run: npm run prettier-check
      - run: npm run eslint-check
      - run: CI=true npm test
  adminapp-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: adminapp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - run: npm install
      - run: npm run prettier-check
      - run: npm run eslint-check
      - run: CI=true npm test
